// <auto-generated />
using System;
using DoAnChamSocSucKhoe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnChamSocSucKhoe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208161642_DeleteAllNonAdminUsers")]
    partial class DeleteAllNonAdminUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnChamSocSucKhoe.Areas.Patient.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UseInsurance")
                        .HasColumnType("bit");

                    b.Property<bool>("WantReminder")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChiSoSucKhoe", b =>
                {
                    b.Property<int>("ChiSoSucKhoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiSoSucKhoeId"));

                    b.Property<float>("BMI")
                        .HasColumnType("real");

                    b.Property<float>("CanNang")
                        .HasColumnType("real");

                    b.Property<float>("ChieuCao")
                        .HasColumnType("real");

                    b.Property<float>("DuongHuyet")
                        .HasColumnType("real");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HuyetAp")
                        .HasColumnType("int");

                    b.Property<string>("LoaiChiSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDo")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NhipTim")
                        .HasColumnType("int");

                    b.HasKey("ChiSoSucKhoeId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ChiSoSucKhoes");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChiTietKeHoachDinhDuong", b =>
                {
                    b.Property<int>("ChiTietKeHoachDinhDuongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietKeHoachDinhDuongId"));

                    b.Property<int>("KeHoachDinhDuongId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonAn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoLuong")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ChiTietKeHoachDinhDuongId");

                    b.HasIndex("KeHoachDinhDuongId");

                    b.ToTable("ChiTietKeHoachDinhDuongs");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChiTietKeHoachTapLuyen", b =>
                {
                    b.Property<int>("ChiTietKeHoachTapLuyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietKeHoachTapLuyenId"));

                    b.Property<string>("BaiTap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KeHoachTapLuyenId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLanLap")
                        .HasColumnType("int");

                    b.Property<int>("ThoiGian")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ChiTietKeHoachTapLuyenId");

                    b.HasIndex("KeHoachTapLuyenId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ChiTietKeHoachTapLuyens");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChuyenGia", b =>
                {
                    b.Property<string>("ChuyenGiaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChungChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuyenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KinhNghiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiCongTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ChuyenGiaId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ChuyenGias");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.DanhGiaChuyenGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BinhLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuyenGiaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NguoiDungId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SoSao")
                        .HasColumnType("int");

                    b.Property<int?>("TuVanSucKhoeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChuyenGiaId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("TuVanSucKhoeId")
                        .IsUnique()
                        .HasFilter("[TuVanSucKhoeId] IS NOT NULL");

                    b.ToTable("DanhGiaChuyenGias");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.FileHoSo", b =>
                {
                    b.Property<int>("FileHoSoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileHoSoId"));

                    b.Property<string>("DuongDan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoSoSucKhoeId")
                        .HasColumnType("int");

                    b.Property<long>("KichThuoc")
                        .HasColumnType("bigint");

                    b.Property<string>("LoaiFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTaiLen")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiTaiLenId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenFile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileHoSoId");

                    b.HasIndex("HoSoSucKhoeId");

                    b.HasIndex("NguoiTaiLenId");

                    b.ToTable("FileHoSos");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.HoSoSucKhoe", b =>
                {
                    b.Property<int>("HoSoSucKhoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoSoSucKhoeId"));

                    b.Property<decimal>("CanNang")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("ChanDoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ChieuCao")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("DiUng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DuongHuyet")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HuyetApTamThu")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("HuyetApTamTruong")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("LoiSong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NhipTim")
                        .HasColumnType("int");

                    b.Property<string>("NhomMau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuongPhapDieuTri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThuocDangDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TienSuBenh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TienSuGiaDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HoSoSucKhoeId");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("HoSoSucKhoes");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.KeHoachDinhDuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KeHoachDinhDuongId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKeHoach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("KeHoachDinhDuongs");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.KeHoachTapLuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KeHoachTapLuyenId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKeHoach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("KeHoachTapLuyens");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.LichHen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BacSiId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BenhNhanId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChanDoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuyenGiaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonThuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LichHenId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiLichHen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGioHen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHen")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BacSiId");

                    b.HasIndex("ChuyenGiaId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("LichHens");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.LichSuHoSoSucKhoe", b =>
                {
                    b.Property<int>("LichSuHoSoSucKhoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LichSuHoSoSucKhoeId"));

                    b.Property<int>("HoSoSucKhoeId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiThayDoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThayDoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiThayDoiId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ThayDoiNoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LichSuHoSoSucKhoeId");

                    b.HasIndex("HoSoSucKhoeId");

                    b.HasIndex("NguoiThayDoiId");

                    b.ToTable("LichSuHoSoSucKhoes");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.LichSuSucKhoe", b =>
                {
                    b.Property<int>("LichSuSucKhoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LichSuSucKhoeId"));

                    b.Property<decimal>("CanNang")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ChieuCao")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("DuongHuyet")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HuyetApTamThu")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("HuyetApTamTruong")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("NgayDo")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NhipTim")
                        .HasColumnType("int");

                    b.HasKey("LichSuSucKhoeId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("LichSuSucKhoes");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("MediaType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TuVanSucKhoeId")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("TuVanSucKhoeId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.NguoiChamSocBenhNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BenhNhanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiChamSocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QuanHe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BenhNhanId");

                    b.HasIndex("NguoiChamSocId");

                    b.ToTable("NguoiChamSocBenhNhans");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.NguoiDung", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("VaiTroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("VaiTroId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.NhacNhoSucKhoe", b =>
                {
                    b.Property<int>("NhacNhoSucKhoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhacNhoSucKhoeId"));

                    b.Property<bool>("DaThucHien")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiNhacNho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NhacNhoSucKhoeId");

                    b.ToTable("NhacNhoSucKhoes");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.PhanHoiSucKhoe", b =>
                {
                    b.Property<int>("PhanHoiSucKhoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhanHoiSucKhoeId"));

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("PhanHoiSucKhoeId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("PhanHoiSucKhoes");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ThongBaoBacSi", b =>
                {
                    b.Property<int>("ThongBaoBacSiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThongBaoBacSiId"));

                    b.Property<string>("BacSiId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ThongBaoBacSiId");

                    b.HasIndex("BacSiId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ThongBaoBacSis");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.TuVanSucKhoe", b =>
                {
                    b.Property<int>("TuVanSucKhoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TuVanSucKhoeId"));

                    b.Property<string>("ChuyenGiaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTraLoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("TuVanSucKhoeId");

                    b.HasIndex("ChuyenGiaId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("TuVanSucKhoes");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.VaiTro", b =>
                {
                    b.Property<int>("VaiTroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaiTroId"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VaiTroId");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChiSoSucKhoe", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany("ChiSoSucKhoes")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChiTietKeHoachDinhDuong", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.KeHoachDinhDuong", "KeHoachDinhDuong")
                        .WithMany("ChiTietKeHoachDinhDuongs")
                        .HasForeignKey("KeHoachDinhDuongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeHoachDinhDuong");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChiTietKeHoachTapLuyen", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.KeHoachTapLuyen", "KeHoachTapLuyen")
                        .WithMany("ChiTietKeHoachTapLuyens")
                        .HasForeignKey("KeHoachTapLuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KeHoachTapLuyen");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChuyenGia", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany("ChuyenGias")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.DanhGiaChuyenGia", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.ChuyenGia", "ChuyenGia")
                        .WithMany("DanhGiaDaNhan")
                        .HasForeignKey("ChuyenGiaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhGiaDaGui")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DoAnChamSocSucKhoe.Models.TuVanSucKhoe", "TuVanSucKhoe")
                        .WithOne("DanhGia")
                        .HasForeignKey("DoAnChamSocSucKhoe.Models.DanhGiaChuyenGia", "TuVanSucKhoeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ChuyenGia");

                    b.Navigation("NguoiDung");

                    b.Navigation("TuVanSucKhoe");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.FileHoSo", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.HoSoSucKhoe", "HoSoSucKhoe")
                        .WithMany()
                        .HasForeignKey("HoSoSucKhoeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiTaiLen")
                        .WithMany()
                        .HasForeignKey("NguoiTaiLenId");

                    b.Navigation("HoSoSucKhoe");

                    b.Navigation("NguoiTaiLen");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.HoSoSucKhoe", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithOne("HoSoSucKhoe")
                        .HasForeignKey("DoAnChamSocSucKhoe.Models.HoSoSucKhoe", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.KeHoachDinhDuong", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.KeHoachTapLuyen", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.LichHen", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "BacSi")
                        .WithMany("LichHens")
                        .HasForeignKey("BacSiId");

                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "ChuyenGia")
                        .WithMany()
                        .HasForeignKey("ChuyenGiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("ChuyenGia");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.LichSuHoSoSucKhoe", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.HoSoSucKhoe", "HoSoSucKhoe")
                        .WithMany()
                        .HasForeignKey("HoSoSucKhoeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiThayDoi")
                        .WithMany()
                        .HasForeignKey("NguoiThayDoiId");

                    b.Navigation("HoSoSucKhoe");

                    b.Navigation("NguoiThayDoi");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.LichSuSucKhoe", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.Message", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAnChamSocSucKhoe.Models.TuVanSucKhoe", "TuVanSucKhoe")
                        .WithMany("Messages")
                        .HasForeignKey("TuVanSucKhoeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");

                    b.Navigation("TuVanSucKhoe");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.NguoiChamSocBenhNhan", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "BenhNhan")
                        .WithMany()
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiChamSoc")
                        .WithMany()
                        .HasForeignKey("NguoiChamSocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BenhNhan");

                    b.Navigation("NguoiChamSoc");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.NguoiDung", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.PhanHoiSucKhoe", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ThongBaoBacSi", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "BacSi")
                        .WithMany()
                        .HasForeignKey("BacSiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.TuVanSucKhoe", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.ChuyenGia", "ChuyenGia")
                        .WithMany("TuVanSucKhoes")
                        .HasForeignKey("ChuyenGiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuyenGia");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChuyenGia", b =>
                {
                    b.Navigation("DanhGiaDaNhan");

                    b.Navigation("TuVanSucKhoes");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.KeHoachDinhDuong", b =>
                {
                    b.Navigation("ChiTietKeHoachDinhDuongs");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.KeHoachTapLuyen", b =>
                {
                    b.Navigation("ChiTietKeHoachTapLuyens");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.NguoiDung", b =>
                {
                    b.Navigation("ChiSoSucKhoes");

                    b.Navigation("ChuyenGias");

                    b.Navigation("DanhGiaDaGui");

                    b.Navigation("HoSoSucKhoe");

                    b.Navigation("LichHens");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.TuVanSucKhoe", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
