// <auto-generated />
using System;
using DoAnChamSocSucKhoe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnChamSocSucKhoe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250412164555_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnChamSocSucKhoe.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChiSoSucKhoe", b =>
                {
                    b.Property<int>("ChiSoSucKhoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiSoSucKhoeId"));

                    b.Property<float>("BMI")
                        .HasColumnType("real");

                    b.Property<float>("CanNang")
                        .HasColumnType("real");

                    b.Property<float>("ChieuCao")
                        .HasColumnType("real");

                    b.Property<float>("DuongHuyet")
                        .HasColumnType("real");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HuyetAp")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDo")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("NhipTim")
                        .HasColumnType("int");

                    b.HasKey("ChiSoSucKhoeId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ChiSoSucKhoe");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChiTietKeHoachDinhDuong", b =>
                {
                    b.Property<int>("ChiTietKeHoachDinhDuongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietKeHoachDinhDuongId"));

                    b.Property<int>("KeHoachDinhDuongId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonAn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ChiTietKeHoachDinhDuongId");

                    b.HasIndex("KeHoachDinhDuongId");

                    b.ToTable("ChiTietKeHoachDinhDuongs");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChiTietKeHoachTapLuyen", b =>
                {
                    b.Property<int>("ChiTietKeHoachTapLuyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietKeHoachTapLuyenId"));

                    b.Property<string>("BaiTap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KeHoachTapLuyenId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLanLap")
                        .HasColumnType("int");

                    b.Property<int>("ThoiGian")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ChiTietKeHoachTapLuyenId");

                    b.HasIndex("KeHoachTapLuyenId");

                    b.ToTable("ChiTietKeHoachTapLuyens");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChuyenGia", b =>
                {
                    b.Property<int>("ChuyenGiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChuyenGiaId"));

                    b.Property<string>("ChungChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuyenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KinhNghiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiCongTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ChuyenGiaId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ChuyenGia");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.DanhGiaChuyenGia", b =>
                {
                    b.Property<int>("DanhGiaChuyenGiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhGiaChuyenGiaId"));

                    b.Property<int>("ChuyenGiaId")
                        .HasColumnType("int");

                    b.Property<int>("DiemSo")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DanhGiaChuyenGiaId");

                    b.HasIndex("ChuyenGiaId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("DanhGiaChuyenGias");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.HoSoSucKhoe", b =>
                {
                    b.Property<int>("HoSoSucKhoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoSoSucKhoeId"));

                    b.Property<decimal>("CanNang")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ChieuCao")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DuongHuyet")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HuyetApTamThu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("HuyetApTamTruong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("NhipTim")
                        .HasColumnType("int");

                    b.HasKey("HoSoSucKhoeId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("HoSoSucKhoes");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.KeHoachDinhDuong", b =>
                {
                    b.Property<int>("KeHoachDinhDuongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeHoachDinhDuongId"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("TenKeHoach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("KeHoachDinhDuongId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("KeHoachDinhDuongs");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.KeHoachTapLuyen", b =>
                {
                    b.Property<int>("KeHoachTapLuyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeHoachTapLuyenId"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("TenKeHoach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("KeHoachTapLuyenId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("KeHoachTapLuyens");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.LichHen", b =>
                {
                    b.Property<int>("LichHenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LichHenId"));

                    b.Property<int>("ChuyenGiaId")
                        .HasColumnType("int");

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGioHen")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LichHenId");

                    b.HasIndex("ChuyenGiaId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("LichHens");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.LichSuSucKhoe", b =>
                {
                    b.Property<int>("LichSuSucKhoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LichSuSucKhoeId"));

                    b.Property<decimal>("CanNang")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ChieuCao")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DuongHuyet")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HuyetApTamThu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("HuyetApTamTruong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("NgayDo")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("NhipTim")
                        .HasColumnType("int");

                    b.HasKey("LichSuSucKhoeId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("LichSuSucKhoes");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiDungId"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<int>("VaiTroId")
                        .HasColumnType("int");

                    b.HasKey("NguoiDungId");

                    b.HasIndex("VaiTroId");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.NhacNhoSucKhoe", b =>
                {
                    b.Property<int>("NhacNhoSucKhoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhacNhoSucKhoeId"));

                    b.Property<string>("ChuKyLap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LapLai")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianNhac")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("NhacNhoSucKhoeId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("NhacNhoSucKhoe");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.PhanHoiSucKhoe", b =>
                {
                    b.Property<int>("PhanHoiSucKhoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhanHoiSucKhoeId"));

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("PhanHoiSucKhoeId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("PhanHoiSucKhoes");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ThongBaoBacSi", b =>
                {
                    b.Property<int>("ThongBaoBacSiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThongBaoBacSiId"));

                    b.Property<int>("BacSiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ThongBaoBacSiId");

                    b.HasIndex("BacSiId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ThongBaoBacSis");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.TuVanSucKhoe", b =>
                {
                    b.Property<int>("TuVanSucKhoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TuVanSucKhoeId"));

                    b.Property<int>("ChuyenGiaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraLoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("TuVanSucKhoeId");

                    b.HasIndex("ChuyenGiaId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("TuVanSucKhoes");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.VaiTro", b =>
                {
                    b.Property<int>("VaiTroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaiTroId"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VaiTroId");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "67586ba7-5328-43a1-91ea-c4cab88444d6",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "6e6e1cfb-2785-482f-bde0-96d74de081ca",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "8e4818eb-f3c1-4979-8307-4e8666b76a94",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChiSoSucKhoe", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChiTietKeHoachDinhDuong", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.KeHoachDinhDuong", "KeHoachDinhDuong")
                        .WithMany("ChiTietKeHoachDinhDuongs")
                        .HasForeignKey("KeHoachDinhDuongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeHoachDinhDuong");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChiTietKeHoachTapLuyen", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.KeHoachTapLuyen", "KeHoachTapLuyen")
                        .WithMany("ChiTietKeHoachTapLuyens")
                        .HasForeignKey("KeHoachTapLuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeHoachTapLuyen");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChuyenGia", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany("ChuyenGias")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.DanhGiaChuyenGia", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.ChuyenGia", "ChuyenGia")
                        .WithMany("DanhGiaDaNhan")
                        .HasForeignKey("ChuyenGiaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhGiaDaGui")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChuyenGia");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.HoSoSucKhoe", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.KeHoachDinhDuong", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.KeHoachTapLuyen", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.LichHen", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "ChuyenGia")
                        .WithMany()
                        .HasForeignKey("ChuyenGiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChuyenGia");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.LichSuSucKhoe", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.NguoiDung", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.NhacNhoSucKhoe", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.PhanHoiSucKhoe", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ThongBaoBacSi", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "BacSi")
                        .WithMany()
                        .HasForeignKey("BacSiId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.TuVanSucKhoe", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Models.ChuyenGia", "ChuyenGia")
                        .WithMany("TuVanSucKhoes")
                        .HasForeignKey("ChuyenGiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnChamSocSucKhoe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenGia");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnChamSocSucKhoe.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DoAnChamSocSucKhoe.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.ChuyenGia", b =>
                {
                    b.Navigation("DanhGiaDaNhan");

                    b.Navigation("TuVanSucKhoes");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.KeHoachDinhDuong", b =>
                {
                    b.Navigation("ChiTietKeHoachDinhDuongs");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.KeHoachTapLuyen", b =>
                {
                    b.Navigation("ChiTietKeHoachTapLuyens");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.NguoiDung", b =>
                {
                    b.Navigation("ChuyenGias");

                    b.Navigation("DanhGiaDaGui");
                });

            modelBuilder.Entity("DoAnChamSocSucKhoe.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
